apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: masters-cluster
  namespace: kafka
  labels:
    app: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    # authorization:
    #   type: simple
    #   superUsers:
    #     - CN=kafkauser-matej
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      # - name: external
      #   port: 9094
      #   type: nodeport
      #   tls: false
      - name: externallb
        port: 9095
        type: loadbalancer
        tls: false
      - name: externaltls
        port: 9096
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          brokers:
            - broker: 0 # Needed only for minikube
              advertisedHost: 109.60.33.45
              advertisedPort: 30096
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - kafka-cluster-kafka
                topologyKey: kubernetes.io/hostname
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
      compression.type: snappy
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "WARN"

  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "WARN"
  entityOperator:
    topicOperator: {}
    userOperator: {}
