apiVersion: v1
kind: Service
metadata:
  labels:
    app: schema-registry
  name: schema-registry
  namespace: kafka
spec:
  ports:
    - name: schema-registry-rest
      port: 8081
      targetPort: 8081
  selector:
    app: schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schema-registry
  name: schema-registry
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.3.3
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: masters-cluster-kafka-bootstrap:9092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
          resources:
            limits:
              cpu: 400m
              memory: 500Mi              
          ports:
            - containerPort: 8081
      hostname: schema-registry
      enableServiceLinks: false
