apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.7.0
          env:
            - name: ELASTICSEARCH_HOST
              value: "masters-es-internal-http.elk"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: masters-es-elastic-user
                  key: elastic
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config-volume
              mountPath: /usr/share/logstash/config/
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline/
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
      volumes:
        - name: logstash-config-volume
          configMap:
            name: logstash-config
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-config-pipelines
