apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.yml: |

    log.level: info
    config.support_escapes: true

  pipelines.yml: |

    - pipeline.id: kafka-source
      path.config: '/usr/share/logstash/pipeline/kafka-source.conf'
