apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstream-aggregator
  labels:
    app: kstream-aggregator
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstream-aggregator
  template:
    metadata:
      name: kstream-aggregator
      labels:
        app: kstream-aggregator
    spec:
      containers:
        - name: kstream-aggregator
          image: mcubek/log_aggregation_kstream:1.0
          imagePullPolicy: Always
          env:
            - name: INPUT_TOPIC_PATTERN
              value: "logs-.*"
            - name: OUTPUT_TOPIC
              value: "aggregated-log-errors"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: masters-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      restartPolicy: Always
      